# Generated by Django 3.1.1 on 2020-09-23 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 23, 23, 28, 9, 688056, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Repositories',
        ),
    ]
