# Generated by Django 3.1.1 on 2020-09-24 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import github_repos.models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0002_auto_20200923_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 21, 22, 2, 471088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=200, validators=[github_repos.models.validate_github]),
        ),
    ]
