# Generated by Django 3.1.1 on 2020-09-24 21:31

from django.db import migrations, models
import django.utils.timezone
import github_repos.models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0003_auto_20200924_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='even_field',
            field=models.IntegerField(default=0, validators=[github_repos.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
